### ISSUE TITLE
Time doesn't change when clicked on

### ISSUE THREAD

**Issue by atourkow** [JonDum/ractive-datepicker#1]
In the demo page, when I click on the time and mouse wheel to change it, it doesn't update.  However, the AM/PM works.

**Comment by sarendipitee** [comment]
What browser/os?

**Comment by atourkow** [comment]
Windows 10 Home
Chrome: Version 49.0.2623.112 m

**Comment by sarendipitee** [comment]
TIL Chrome on Mac has Element.scrollTo() and Chrome on Windows doesn't. Changed it to use scrollTop instead and it seems to be working on Windows now.

**Comment by atourkow** [comment]
Perfect!   Good job and nice plugin!
